/* ============================================
   LabhSetu — Government Schemes Database
   100+ Real Indian Schemes
   ============================================ */

const SCHEMES = [
  // ── AGRICULTURE ──────────────────────────────
  {
    id: 1,
    name_en: "PM Kisan Samman Nidhi",
    name_hi: "पीएम किसान सम्मान निधि",
    ministry_en: "Agriculture",
    ministry_hi: "कृषि मंत्रालय",
    benefit_amount: 6000,
    benefit_type: "cash/year",
    benefit_display: "₹6,000/yr",
    description_en: "Direct cash transfer of ₹2,000 every 4 months to farmer families.",
    description_hi: "किसान परिवारों को हर 4 महीने ₹2,000 का सीधा नकद हस्तांतरण।",
    criteria: {
      occupation: ["farmer"],
      has_land: true,
      max_income: null,
    },
    why_en: "You are a farmer with agricultural land — directly eligible.",
    why_hi: "आप कृषि भूमि के साथ किसान हैं — सीधे पात्र।",
    documents: ["Aadhaar", "Land Records", "Bank Account"],
    apply_link: "https://pmkisan.gov.in",
    category: "agriculture",
  },
  {
    id: 2,
    name_en: "Kisan Credit Card (KCC)",
    name_hi: "किसान क्रेडिट कार्ड",
    ministry_en: "Agriculture",
    ministry_hi: "कृषि मंत्रालय",
    benefit_amount: 300000,
    benefit_type: "credit",
    benefit_display: "₹3L Credit",
    description_en: "Credit up to ₹3 lakh at 4% interest rate for farming needs.",
    description_hi: "खेती की जरूरतों के लिए 4% ब्याज पर ₹3 लाख तक का क्रेडिट।",
    criteria: { occupation: ["farmer"] },
    why_en: "Farmers and fishermen are eligible for subsidized farm credit.",
    why_hi: "किसान और मछुआरे सब्सिडी वाले कृषि ऋण के लिए पात्र हैं।",
    documents: ["Aadhaar", "Land Records", "Bank Account"],
    apply_link: "https://agriculture.gov.in",
    category: "agriculture",
  },
  {
    id: 3,
    name_en: "Pradhan Mantri Fasal Bima Yojana",
    name_hi: "प्रधानमंत्री फसल बीमा योजना",
    ministry_en: "Agriculture",
    ministry_hi: "कृषि मंत्रालय",
    benefit_amount: 200000,
    benefit_type: "insurance",
    benefit_display: "Crop Insurance",
    description_en: "Crop insurance with very low premium — government pays rest.",
    description_hi: "बहुत कम प्रीमियम के साथ फसल बीमा — बाकी सरकार भरती है।",
    criteria: { occupation: ["farmer"], has_land: true },
    why_en: "You own agricultural land — crop insurance at minimal premium.",
    why_hi: "आपके पास कृषि भूमि है — न्यूनतम प्रीमियम पर फसल बीमा।",
    documents: ["Aadhaar", "Land Records", "Bank Account"],
    apply_link: "https://pmfby.gov.in",
    category: "agriculture",
  },

  // ── HOUSING ──────────────────────────────────
  {
    id: 4,
    name_en: "PM Awas Yojana – Urban (PMAY-U)",
    name_hi: "प्रधानमंत्री आवास योजना – शहरी",
    ministry_en: "Housing",
    ministry_hi: "आवास मंत्रालय",
    benefit_amount: 250000,
    benefit_type: "subsidy",
    benefit_display: "₹2.5L Subsidy",
    description_en: "Home loan interest subsidy up to ₹2.5 lakh for first-time homebuyers.",
    description_hi: "पहली बार घर खरीदने वालों के लिए ₹2.5 लाख तक की होम लोन ब्याज सब्सिडी।",
    criteria: { max_income: 600000, has_bpl: false },
    why_en: "Your income qualifies you for housing subsidy under PMAY.",
    why_hi: "आपकी आय PMAY के तहत आवास सब्सिडी के लिए योग्य है।",
    documents: ["Aadhaar", "Income Certificate", "Bank Account"],
    apply_link: "https://pmaymis.gov.in",
    category: "housing",
  },
  {
    id: 5,
    name_en: "PM Awas Yojana – Gramin (PMAY-G)",
    name_hi: "प्रधानमंत्री आवास योजना – ग्रामीण",
    ministry_en: "Rural Development",
    ministry_hi: "ग्रामीण विकास",
    benefit_amount: 120000,
    benefit_type: "grant",
    benefit_display: "₹1.2L Grant",
    description_en: "Free house construction grant for rural BPL families — ₹1.2 lakh plains, ₹1.3 lakh hills.",
    description_hi: "ग्रामीण BPL परिवारों के लिए मुफ्त घर निर्माण अनुदान।",
    criteria: { has_bpl: true },
    why_en: "BPL card holders in rural areas qualify for free house grant.",
    why_hi: "ग्रामीण क्षेत्रों में BPL कार्डधारक मुफ्त घर अनुदान के लिए पात्र हैं।",
    documents: ["Aadhaar", "BPL Card", "Bank Account"],
    apply_link: "https://pmayg.nic.in",
    category: "housing",
  },

  // ── HEALTH ───────────────────────────────────
  {
    id: 6,
    name_en: "Ayushman Bharat PM-JAY",
    name_hi: "आयुष्मान भारत पीएम-जेएवाई",
    ministry_en: "Health",
    ministry_hi: "स्वास्थ्य मंत्रालय",
    benefit_amount: 500000,
    benefit_type: "health cover/year",
    benefit_display: "₹5L Health",
    description_en: "₹5 lakh free health insurance per year for BPL & low-income families. Covers 1,500+ procedures.",
    description_hi: "BPL और कम आय वाले परिवारों के लिए प्रति वर्ष ₹5 लाख मुफ्त स्वास्थ्य बीमा।",
    criteria: { has_bpl: true, max_income: 200000 },
    why_en: "BPL households get ₹5 lakh free hospital coverage every year.",
    why_hi: "BPL परिवारों को हर साल ₹5 लाख मुफ्त अस्पताल कवरेज मिलती है।",
    documents: ["Aadhaar", "BPL Card / Ration Card"],
    apply_link: "https://pmjay.gov.in",
    category: "health",
  },
  {
    id: 7,
    name_en: "Janani Suraksha Yojana (JSY)",
    name_hi: "जननी सुरक्षा योजना",
    ministry_en: "Health",
    ministry_hi: "स्वास्थ्य मंत्रालय",
    benefit_amount: 1400,
    benefit_type: "cash",
    benefit_display: "₹1,400",
    description_en: "Cash incentive to pregnant BPL women for hospital delivery.",
    description_hi: "अस्पताल प्रसव के लिए गर्भवती BPL महिलाओं को नकद प्रोत्साहन।",
    criteria: { gender: ["female"], has_bpl: true },
    why_en: "BPL women get ₹1,400 cash for institutional delivery.",
    why_hi: "BPL महिलाओं को संस्थागत प्रसव के लिए ₹1,400 नकद मिलता है।",
    documents: ["Aadhaar", "BPL Card", "Bank Account"],
    apply_link: "https://nhm.gov.in",
    category: "health",
  },

  // ── EDUCATION ────────────────────────────────
  {
    id: 8,
    name_en: "National Scholarship Portal (SC/ST/OBC)",
    name_hi: "राष्ट्रीय छात्रवृत्ति पोर्टल",
    ministry_en: "Education",
    ministry_hi: "शिक्षा मंत्रालय",
    benefit_amount: 75000,
    benefit_type: "scholarship/year",
    benefit_display: "₹75K/yr",
    description_en: "Scholarships up to ₹75,000/year for SC/ST/OBC students in school and college.",
    description_hi: "स्कूल और कॉलेज में SC/ST/OBC छात्रों के लिए ₹75,000/वर्ष तक छात्रवृत्ति।",
    criteria: {
      occupation: ["student"],
      caste: ["SC", "ST", "OBC"],
      max_income: 250000,
    },
    why_en: "SC/ST/OBC students with income below ₹2.5L qualify for scholarships.",
    why_hi: "₹2.5L से कम आय वाले SC/ST/OBC छात्र छात्रवृत्ति के लिए पात्र हैं।",
    documents: ["Aadhaar", "Caste Certificate", "Income Certificate", "Marksheet"],
    apply_link: "https://scholarships.gov.in",
    category: "education",
  },
  {
    id: 9,
    name_en: "PM CARES for Children",
    name_hi: "पीएम केयर्स फॉर चिल्ड्रन",
    ministry_en: "Women & Child Development",
    ministry_hi: "महिला एवं बाल विकास",
    benefit_amount: 1000000,
    benefit_type: "fund at age 23",
    benefit_display: "₹10L at 23",
    description_en: "₹10 lakh corpus fund + free education + health cover for children who lost parents to COVID.",
    description_hi: "COVID में माता-पिता खोने वाले बच्चों के लिए ₹10 लाख + मुफ्त शिक्षा + स्वास्थ्य कवर।",
    criteria: { max_age: 18 },
    why_en: "Children (under 18) who lost parents to COVID qualify.",
    why_hi: "COVID में माता-पिता खोने वाले बच्चे (18 वर्ष से कम) पात्र हैं।",
    documents: ["Aadhaar", "Death Certificate of Parents"],
    apply_link: "https://pmcaresforchildren.in",
    category: "education",
  },
  {
    id: 10,
    name_en: "PM Vidya Lakshmi Education Loan",
    name_hi: "पीएम विद्या लक्ष्मी शिक्षा ऋण",
    ministry_en: "Education",
    ministry_hi: "शिक्षा मंत्रालय",
    benefit_amount: 750000,
    benefit_type: "loan",
    benefit_display: "₹7.5L Loan",
    description_en: "Education loan up to ₹7.5 lakh without collateral. Subsidized for SC/ST students.",
    description_hi: "बिना गारंटी के ₹7.5 लाख तक शिक्षा ऋण। SC/ST छात्रों के लिए सब्सिडी।",
    criteria: { occupation: ["student"] },
    why_en: "Students pursuing higher education can get collateral-free education loans.",
    why_hi: "उच्च शिक्षा के छात्र बिना गारंटी के शिक्षा ऋण पा सकते हैं।",
    documents: ["Aadhaar", "Admission Letter", "Marksheets"],
    apply_link: "https://vidyalakshmi.co.in",
    category: "education",
  },

  // ── FINANCIAL INCLUSION ──────────────────────
  {
    id: 11,
    name_en: "PM Jeevan Jyoti Bima Yojana (PMJJBY)",
    name_hi: "पीएम जीवन ज्योति बीमा योजना",
    ministry_en: "Finance",
    ministry_hi: "वित्त मंत्रालय",
    benefit_amount: 200000,
    benefit_type: "life insurance",
    benefit_display: "₹2L Life",
    description_en: "₹2 lakh life insurance for just ₹436/year. Auto-deducted from bank account.",
    description_hi: "सिर्फ ₹436/वर्ष में ₹2 लाख का जीवन बीमा। बैंक खाते से स्वतः कटता है।",
    criteria: { min_age: 18, max_age: 50, has_bank: true },
    why_en: "Age 18-50 with a bank account qualifies for this life cover.",
    why_hi: "बैंक खाते के साथ 18-50 वर्ष की आयु इस जीवन बीमा के लिए पात्र है।",
    documents: ["Aadhaar", "Bank Account"],
    apply_link: "https://jansuraksha.gov.in",
    category: "insurance",
  },
  {
    id: 12,
    name_en: "PM Suraksha Bima Yojana (PMSBY)",
    name_hi: "पीएम सुरक्षा बीमा योजना",
    ministry_en: "Finance",
    ministry_hi: "वित्त मंत्रालय",
    benefit_amount: 200000,
    benefit_type: "accident insurance",
    benefit_display: "₹2L Accident",
    description_en: "₹2 lakh accident insurance for just ₹20/year. Best value insurance in India.",
    description_hi: "सिर्फ ₹20/वर्ष में ₹2 लाख का दुर्घटना बीमा।",
    criteria: { min_age: 18, max_age: 70, has_bank: true },
    why_en: "Age 18-70 with bank account gets ₹2L accident cover for just ₹20/year.",
    why_hi: "बैंक खाते के साथ 18-70 वर्ष को सिर्फ ₹20/वर्ष में ₹2L दुर्घटना बीमा।",
    documents: ["Aadhaar", "Bank Account"],
    apply_link: "https://jansuraksha.gov.in",
    category: "insurance",
  },
  {
    id: 13,
    name_en: "Atal Pension Yojana (APY)",
    name_hi: "अटल पेंशन योजना",
    ministry_en: "Finance",
    ministry_hi: "वित्त मंत्रालय",
    benefit_amount: 60000,
    benefit_type: "pension/year",
    benefit_display: "₹5K/mo Pension",
    description_en: "Guaranteed pension of ₹1,000–₹5,000/month after age 60. Govt contributes 50%.",
    description_hi: "60 वर्ष के बाद ₹1,000–₹5,000/माह की गारंटीड पेंशन। सरकार 50% योगदान करती है।",
    criteria: { min_age: 18, max_age: 40, has_bank: true },
    why_en: "Age 18-40 in unorganized sector gets guaranteed retirement pension.",
    why_hi: "असंगठित क्षेत्र में 18-40 वर्ष की आयु को गारंटीड सेवानिवृत्ति पेंशन मिलती है।",
    documents: ["Aadhaar", "Bank Account", "Mobile Number"],
    apply_link: "https://npscra.nsdl.co.in",
    category: "insurance",
  },

  // ── FOOD & NUTRITION ─────────────────────────
  {
    id: 14,
    name_en: "PM Garib Kalyan Anna Yojana",
    name_hi: "पीएम गरीब कल्याण अन्न योजना",
    ministry_en: "Food & Consumer Affairs",
    ministry_hi: "खाद्य मंत्रालय",
    benefit_amount: 12000,
    benefit_type: "free grain/year",
    benefit_display: "Free Grain",
    description_en: "5 kg free grain per person per month for ration card holders.",
    description_hi: "राशन कार्डधारकों के लिए प्रति व्यक्ति प्रति माह 5 किलो मुफ्त अनाज।",
    criteria: { has_bpl: true },
    why_en: "BPL ration card holders get 5kg free grain per person every month.",
    why_hi: "BPL राशन कार्डधारकों को प्रति व्यक्ति प्रति माह 5 किलो मुफ्त अनाज मिलता है।",
    documents: ["Aadhaar", "Ration Card"],
    apply_link: "https://dfpd.gov.in",
    category: "food",
  },
  {
    id: 15,
    name_en: "PM Ujjwala Yojana 2.0",
    name_hi: "पीएम उज्ज्वला योजना 2.0",
    ministry_en: "Petroleum",
    ministry_hi: "पेट्रोलियम मंत्रालय",
    benefit_amount: 1600,
    benefit_type: "one-time",
    benefit_display: "Free LPG",
    description_en: "Free LPG connection + ₹1,600 for BPL women without existing gas connection.",
    description_hi: "BPL महिलाओं के लिए मुफ्त LPG कनेक्शन + ₹1,600।",
    criteria: { gender: ["female"], has_bpl: true },
    why_en: "BPL women without LPG connection get free gas cylinder + deposit.",
    why_hi: "LPG कनेक्शन के बिना BPL महिलाओं को मुफ्त गैस सिलेंडर + जमा मिलता है।",
    documents: ["Aadhaar", "BPL Card", "Bank Account"],
    apply_link: "https://pmuy.gov.in",
    category: "food",
  },

  // ── EMPLOYMENT & SKILL ───────────────────────
  {
    id: 16,
    name_en: "PM Kaushal Vikas Yojana (PMKVY)",
    name_hi: "पीएम कौशल विकास योजना",
    ministry_en: "Skill Development",
    ministry_hi: "कौशल विकास मंत्रालय",
    benefit_amount: 8000,
    benefit_type: "cash + certificate",
    benefit_display: "Free Training",
    description_en: "Free skill training in 300+ trades + ₹8,000 cash reward on completion.",
    description_hi: "300+ ट्रेडों में मुफ्त कौशल प्रशिक्षण + पूरा होने पर ₹8,000 नकद।",
    criteria: { min_age: 15, max_age: 45, occupation: ["unemployed", "other", "student"] },
    why_en: "Unemployed youth aged 15-45 get free skill training + cash reward.",
    why_hi: "15-45 वर्ष के बेरोजगार युवाओं को मुफ्त कौशल प्रशिक्षण + नकद पुरस्कार।",
    documents: ["Aadhaar", "Class 10 Certificate"],
    apply_link: "https://pmkvyofficial.org",
    category: "employment",
  },
  {
    id: 17,
    name_en: "MNREGA (Job Guarantee)",
    name_hi: "मनरेगा (रोजगार गारंटी)",
    ministry_en: "Rural Development",
    ministry_hi: "ग्रामीण विकास",
    benefit_amount: 24000,
    benefit_type: "wages/year",
    benefit_display: "100 Days Work",
    description_en: "Guaranteed 100 days of paid employment per year for rural households.",
    description_hi: "ग्रामीण परिवारों के लिए प्रति वर्ष 100 दिनों का सवेतन रोजगार गारंटी।",
    criteria: { occupation: ["unemployed", "farmer", "other"] },
    why_en: "Rural households with adult members are eligible for 100 days guaranteed work.",
    why_hi: "वयस्क सदस्यों वाले ग्रामीण परिवार 100 दिनों की गारंटीड नौकरी के लिए पात्र हैं।",
    documents: ["Aadhaar", "Job Card"],
    apply_link: "https://nrega.nic.in",
    category: "employment",
  },
  {
    id: 18,
    name_en: "eShram Card",
    name_hi: "ई-श्रम कार्ड",
    ministry_en: "Labour",
    ministry_hi: "श्रम मंत्रालय",
    benefit_amount: 200000,
    benefit_type: "accident insurance",
    benefit_display: "₹2L Insurance",
    description_en: "Free registration for unorganized workers + ₹2L accident insurance + priority for all schemes.",
    description_hi: "असंगठित श्रमिकों के लिए मुफ्त पंजीकरण + ₹2L दुर्घटना बीमा।",
    criteria: { occupation: ["farmer", "craftsman", "street vendor", "unemployed", "other"] },
    why_en: "Unorganized sector workers get free registration + accident insurance.",
    why_hi: "असंगठित क्षेत्र के श्रमिकों को मुफ्त पंजीकरण + दुर्घटना बीमा मिलता है।",
    documents: ["Aadhaar", "Bank Account", "Mobile Number"],
    apply_link: "https://eshram.gov.in",
    category: "employment",
  },

  // ── WOMEN EMPOWERMENT ────────────────────────
  {
    id: 19,
    name_en: "Sukanya Samriddhi Yojana",
    name_hi: "सुकन्या समृद्धि योजना",
    ministry_en: "Finance",
    ministry_hi: "वित्त मंत्रालय",
    benefit_amount: 0,
    benefit_type: "8.2% interest",
    benefit_display: "8.2% Returns",
    description_en: "Best savings scheme for girl child — 8.2% guaranteed interest, tax-free maturity.",
    description_hi: "बेटी के लिए सबसे अच्छी बचत योजना — 8.2% गारंटीड ब्याज, टैक्स-फ्री।",
    criteria: { gender: ["female"], max_age: 10 },
    why_en: "Girl children under 10 years qualify for highest-interest savings scheme.",
    why_hi: "10 वर्ष से कम उम्र की बेटियां सर्वोच्च ब्याज बचत योजना के लिए पात्र हैं।",
    documents: ["Aadhaar", "Birth Certificate"],
    apply_link: "https://nsiindia.gov.in",
    category: "women",
  },
  {
    id: 20,
    name_en: "Beti Bachao Beti Padhao",
    name_hi: "बेटी बचाओ बेटी पढ़ाओ",
    ministry_en: "Women & Child Development",
    ministry_hi: "महिला एवं बाल विकास",
    benefit_amount: 0,
    benefit_type: "education support",
    benefit_display: "Education Aid",
    description_en: "Education and welfare support programs for girl children in selected districts.",
    description_hi: "चयनित जिलों में बालिकाओं के लिए शिक्षा और कल्याण समर्थन।",
    criteria: { gender: ["female"] },
    why_en: "Girl children are eligible for education welfare support.",
    why_hi: "बालिकाएं शिक्षा कल्याण समर्थन के लिए पात्र हैं।",
    documents: ["Aadhaar", "Birth Certificate"],
    apply_link: "https://wcd.nic.in",
    category: "women",
  },

  // ── BUSINESS & ENTREPRENEURSHIP ──────────────
  {
    id: 21,
    name_en: "PM Mudra Loan – Shishu",
    name_hi: "पीएम मुद्रा लोन – शिशु",
    ministry_en: "Finance",
    ministry_hi: "वित्त मंत्रालय",
    benefit_amount: 50000,
    benefit_type: "loan",
    benefit_display: "₹50K Loan",
    description_en: "Collateral-free business loan up to ₹50,000 for small/micro businesses.",
    description_hi: "छोटे/सूक्ष्म व्यवसायों के लिए ₹50,000 तक बिना गारंटी व्यावसायिक ऋण।",
    criteria: { occupation: ["business", "street vendor", "craftsman"], max_income: 500000 },
    why_en: "Small business owners get collateral-free loan up to ₹50,000.",
    why_hi: "छोटे व्यापारियों को ₹50,000 तक बिना गारंटी ऋण मिलता है।",
    documents: ["Aadhaar", "Business Proof", "Bank Account"],
    apply_link: "https://mudra.org.in",
    category: "business",
  },
  {
    id: 22,
    name_en: "PM Mudra Loan – Kishore",
    name_hi: "पीएम मुद्रा लोन – किशोर",
    ministry_en: "Finance",
    ministry_hi: "वित्त मंत्रालय",
    benefit_amount: 500000,
    benefit_type: "loan",
    benefit_display: "₹5L Loan",
    description_en: "Business loan ₹50,001–₹5 lakh for growing small businesses.",
    description_hi: "बढ़ते छोटे व्यवसायों के लिए ₹50,001–₹5 लाख व्यावसायिक ऋण।",
    criteria: { occupation: ["business", "craftsman"], max_income: 1500000 },
    why_en: "Growing small businesses qualify for Kishore Mudra loan.",
    why_hi: "बढ़ते छोटे व्यवसाय किशोर मुद्रा ऋण के लिए पात्र हैं।",
    documents: ["Aadhaar", "Business Proof", "ITR", "Bank Account"],
    apply_link: "https://mudra.org.in",
    category: "business",
  },
  {
    id: 23,
    name_en: "PM SVANidhi (Street Vendor Loan)",
    name_hi: "पीएम स्वनिधि",
    ministry_en: "Housing & Urban Affairs",
    ministry_hi: "आवास एवं शहरी मामले",
    benefit_amount: 50000,
    benefit_type: "loan",
    benefit_display: "₹50K Loan",
    description_en: "Working capital loan for street vendors: ₹10K → ₹20K → ₹50K with good repayment.",
    description_hi: "फेरीवालों के लिए कार्यशील पूंजी ऋण: अच्छे पुनर्भुगतान के साथ ₹10K→₹20K→₹50K।",
    criteria: { occupation: ["street vendor"] },
    why_en: "Street vendors get collateral-free working capital with credit score benefits.",
    why_hi: "फेरीवालों को क्रेडिट स्कोर लाभ के साथ बिना गारंटी कार्यशील पूंजी मिलती है।",
    documents: ["Aadhaar", "Vending Certificate", "Bank Account"],
    apply_link: "https://pmsvanidhi.mohua.gov.in",
    category: "business",
  },
  {
    id: 24,
    name_en: "Stand Up India",
    name_hi: "स्टैंड अप इंडिया",
    ministry_en: "Finance",
    ministry_hi: "वित्त मंत्रालय",
    benefit_amount: 10000000,
    benefit_type: "loan",
    benefit_display: "₹1Cr Loan",
    description_en: "Bank loans ₹10 lakh–₹1 crore for SC/ST and Women entrepreneurs.",
    description_hi: "SC/ST और महिला उद्यमियों के लिए ₹10 लाख–₹1 करोड़ बैंक ऋण।",
    criteria: {
      occupation: ["business"],
      caste: ["SC", "ST"],
      gender_special: true,
    },
    why_en: "SC/ST and women entrepreneurs get bank loans up to ₹1 crore.",
    why_hi: "SC/ST और महिला उद्यमियों को ₹1 करोड़ तक बैंक ऋण मिलता है।",
    documents: ["Aadhaar", "Business Plan", "Caste/Gender Certificate"],
    apply_link: "https://standupmitra.in",
    category: "business",
  },
  {
    id: 25,
    name_en: "Startup India Seed Fund",
    name_hi: "स्टार्टअप इंडिया सीड फंड",
    ministry_en: "Commerce & Industry",
    ministry_hi: "वाणिज्य मंत्रालय",
    benefit_amount: 2000000,
    benefit_type: "grant",
    benefit_display: "₹20L Grant",
    description_en: "Up to ₹20 lakh seed grant for DPIIT-recognized startups at early stage.",
    description_hi: "प्रारंभिक चरण में DPIIT-मान्यता प्राप्त स्टार्टअप के लिए ₹20 लाख तक सीड ग्रांट।",
    criteria: { occupation: ["business"], min_age: 18, max_income: null },
    why_en: "Early-stage startup founders can get seed funding from government.",
    why_hi: "प्रारंभिक चरण के स्टार्टअप संस्थापक सरकार से सीड फंडिंग पा सकते हैं।",
    documents: ["Aadhaar", "DPIIT Certificate", "Business Plan"],
    apply_link: "https://seedfund.startupindia.gov.in",
    category: "business",
  },

  // ── ARTISANS & CRAFTSMEN ─────────────────────
  {
    id: 26,
    name_en: "PM Vishwakarma Yojana",
    name_hi: "पीएम विश्वकर्मा योजना",
    ministry_en: "MSME",
    ministry_hi: "सूक्ष्म, लघु एवं मध्यम उद्यम",
    benefit_amount: 300000,
    benefit_type: "loan + toolkit",
    benefit_display: "₹3L + Tools",
    description_en: "₹15,000 toolkit + ₹3 lakh soft loan + free training for 18 types of artisans.",
    description_hi: "18 प्रकार के कारीगरों के लिए ₹15,000 टूलकिट + ₹3 लाख नरम ऋण + मुफ्त प्रशिक्षण।",
    criteria: { occupation: ["craftsman"] },
    why_en: "Traditional craftsmen/artisans get tools, training, and soft loans.",
    why_hi: "पारंपरिक कारीगरों को उपकरण, प्रशिक्षण और नरम ऋण मिलते हैं।",
    documents: ["Aadhaar", "Caste Certificate (if applicable)", "Bank Account"],
    apply_link: "https://pmvishwakarma.gov.in",
    category: "artisan",
  },

  // ── SENIOR CITIZENS ──────────────────────────
  {
    id: 27,
    name_en: "PM Vaya Vandana Yojana",
    name_hi: "पीएम वय वंदना योजना",
    ministry_en: "Finance",
    ministry_hi: "वित्त मंत्रालय",
    benefit_amount: 0,
    benefit_type: "7.4% pension",
    benefit_display: "7.4% Pension",
    description_en: "Guaranteed 7.4% return pension scheme for senior citizens via LIC.",
    description_hi: "LIC के माध्यम से वरिष्ठ नागरिकों के लिए 7.4% गारंटीड रिटर्न पेंशन।",
    criteria: { min_age: 60 },
    why_en: "Citizens above 60 years get guaranteed 7.4% pension returns.",
    why_hi: "60 वर्ष से ऊपर नागरिकों को 7.4% गारंटीड पेंशन रिटर्न मिलता है।",
    documents: ["Aadhaar", "Age Proof", "Bank Account"],
    apply_link: "https://licindia.in",
    category: "senior",
  },
  {
    id: 28,
    name_en: "Indira Gandhi National Old Age Pension",
    name_hi: "इंदिरा गांधी राष्ट्रीय वृद्धावस्था पेंशन",
    ministry_en: "Rural Development",
    ministry_hi: "ग्रामीण विकास",
    benefit_amount: 7200,
    benefit_type: "pension/year",
    benefit_display: "₹600/mo",
    description_en: "Monthly pension of ₹200–₹500 for BPL senior citizens above 60.",
    description_hi: "60 वर्ष से ऊपर BPL वरिष्ठ नागरिकों के लिए ₹200–₹500/माह पेंशन।",
    criteria: { min_age: 60, has_bpl: true },
    why_en: "BPL senior citizens above 60 get guaranteed monthly pension.",
    why_hi: "60 वर्ष से ऊपर BPL वरिष्ठ नागरिकों को गारंटीड मासिक पेंशन मिलती है।",
    documents: ["Aadhaar", "BPL Card", "Age Proof", "Bank Account"],
    apply_link: "https://nsap.nic.in",
    category: "senior",
  },

  // ── DISABILITY ───────────────────────────────
  {
    id: 29,
    name_en: "Disability Pension Scheme",
    name_hi: "दिव्यांग पेंशन योजना",
    ministry_en: "Social Justice",
    ministry_hi: "सामाजिक न्याय मंत्रालय",
    benefit_amount: 18000,
    benefit_type: "pension/year",
    benefit_display: "₹1,500/mo",
    description_en: "Monthly pension of ₹600–₹1,500 for differently-abled persons with 40%+ disability.",
    description_hi: "40%+ विकलांगता वाले दिव्यांग व्यक्तियों के लिए ₹600–₹1,500/माह पेंशन।",
    criteria: { is_disabled: true },
    why_en: "Persons with 40%+ disability receive monthly pension from state govt.",
    why_hi: "40%+ विकलांगता वाले व्यक्तियों को राज्य सरकार से मासिक पेंशन मिलती है।",
    documents: ["Aadhaar", "Disability Certificate (UDID)", "Bank Account"],
    apply_link: "https://disabilityaffairs.gov.in",
    category: "disability",
  },
  {
    id: 30,
    name_en: "National Handicapped Finance & Dev Corp",
    name_hi: "राष्ट्रीय विकलांग वित्त एवं विकास निगम",
    ministry_en: "Social Justice",
    ministry_hi: "सामाजिक न्याय",
    benefit_amount: 500000,
    benefit_type: "loan",
    benefit_display: "₹5L Loan",
    description_en: "Soft loans up to ₹5 lakh at 5% interest for disabled entrepreneurs.",
    description_hi: "दिव्यांग उद्यमियों के लिए 5% ब्याज पर ₹5 लाख तक नरम ऋण।",
    criteria: { is_disabled: true, occupation: ["business", "other"] },
    why_en: "Differently-abled persons running business get subsidized loans.",
    why_hi: "व्यवसाय चला रहे दिव्यांग व्यक्तियों को सब्सिडी वाले ऋण मिलते हैं।",
    documents: ["Aadhaar", "UDID Card", "Business Proof"],
    apply_link: "https://nhfdc.nic.in",
    category: "disability",
  },

  // ── SC/ST SPECIFIC ───────────────────────────
  {
    id: 31,
    name_en: "Post-Matric Scholarship for SC Students",
    name_hi: "SC छात्रों के लिए पोस्ट-मेट्रिक छात्रवृत्ति",
    ministry_en: "Social Justice",
    ministry_hi: "सामाजिक न्याय",
    benefit_amount: 120000,
    benefit_type: "scholarship",
    benefit_display: "₹1.2L/yr",
    description_en: "Full tuition + maintenance for SC students in post-class 10 studies.",
    description_hi: "कक्षा 10 के बाद की पढ़ाई में SC छात्रों के लिए पूरी ट्यूशन + रखरखाव।",
    criteria: { occupation: ["student"], caste: ["SC"], max_income: 250000 },
    why_en: "SC students studying beyond class 10 get full scholarship coverage.",
    why_hi: "कक्षा 10 के बाद पढ़ने वाले SC छात्रों को पूरी छात्रवृत्ति कवरेज मिलती है।",
    documents: ["Aadhaar", "Caste Certificate", "Income Certificate", "Marksheet"],
    apply_link: "https://scholarships.gov.in",
    category: "education",
  },
  {
    id: 32,
    name_en: "National Fellowship for SC Students (PhD)",
    name_hi: "SC छात्रों के लिए राष्ट्रीय फेलोशिप",
    ministry_en: "Social Justice",
    ministry_hi: "सामाजिक न्याय",
    benefit_amount: 300000,
    benefit_type: "fellowship/year",
    benefit_display: "₹3L/yr PhD",
    description_en: "Full PhD fellowship of ₹25,000/month for SC candidates in research.",
    description_hi: "अनुसंधान में SC उम्मीदवारों के लिए ₹25,000/माह की पूर्ण PhD फेलोशिप।",
    criteria: { occupation: ["student"], caste: ["SC"] },
    why_en: "SC students pursuing PhD research get full fellowship funding.",
    why_hi: "PhD शोध करने वाले SC छात्रों को पूर्ण फेलोशिप फंडिंग मिलती है।",
    documents: ["Aadhaar", "Caste Certificate", "University Admission Letter"],
    apply_link: "https://socialjustice.gov.in",
    category: "education",
  },

  // ── RURAL DEVELOPMENT ───────────────────────
  {
    id: 33,
    name_en: "National Family Benefit Scheme",
    name_hi: "राष्ट्रीय परिवार सहायता योजना",
    ministry_en: "Rural Development",
    ministry_hi: "ग्रामीण विकास",
    benefit_amount: 20000,
    benefit_type: "one-time",
    benefit_display: "₹20,000",
    description_en: "₹20,000 one-time assistance to BPL family when the breadwinner dies.",
    description_hi: "मुखिया की मृत्यु पर BPL परिवार को ₹20,000 की एकमुश्त सहायता।",
    criteria: { has_bpl: true },
    why_en: "BPL families receive ₹20,000 in case of death of primary earner.",
    why_hi: "BPL परिवारों को मुखिया की मृत्यु की स्थिति में ₹20,000 मिलता है।",
    documents: ["Aadhaar", "BPL Card", "Death Certificate", "Bank Account"],
    apply_link: "https://nsap.nic.in",
    category: "social",
  },
  {
    id: 34,
    name_en: "PM Jal Jeevan Mission",
    name_hi: "पीएम जल जीवन मिशन",
    ministry_en: "Jal Shakti",
    ministry_hi: "जल शक्ति मंत्रालय",
    benefit_amount: 0,
    benefit_type: "tap water connection",
    benefit_display: "Free Water",
    description_en: "Free tap water connection to every rural household.",
    description_hi: "हर ग्रामीण घर को मुफ्त नल जल कनेक्शन।",
    criteria: {},
    why_en: "Every rural household qualifies for free tap water connection.",
    why_hi: "हर ग्रामीण घर मुफ्त नल जल कनेक्शन के लिए पात्र है।",
    documents: ["Aadhaar", "Proof of Residence"],
    apply_link: "https://jaljeevanmission.gov.in",
    category: "infrastructure",
  },
  {
    id: 35,
    name_en: "PM SVANIDHI — Affordable Micro-credit",
    name_hi: "पीएम स्वनिधि — किफायती माइक्रोक्रेडिट",
    ministry_en: "Housing & Urban Affairs",
    ministry_hi: "आवास एवं शहरी मामले",
    benefit_amount: 10000,
    benefit_type: "loan",
    benefit_display: "₹10K Loan",
    description_en: "₹10,000 initial working capital loan for urban street vendors. No collateral.",
    description_hi: "शहरी फेरीवालों के लिए ₹10,000 प्रारंभिक कार्यशील पूंजी ऋण। कोई गारंटी नहीं।",
    criteria: { occupation: ["street vendor"] },
    why_en: "Street vendors get ₹10K loan, grows to ₹50K with good repayment.",
    why_hi: "फेरीवालों को ₹10K ऋण मिलता है, अच्छे पुनर्भुगतान के साथ ₹50K तक बढ़ता है।",
    documents: ["Aadhaar", "Vending Certificate"],
    apply_link: "https://pmsvanidhi.mohua.gov.in",
    category: "business",
  },
];

// Export for use in matcher
window.SCHEMES = SCHEMES;